name: Postman Test

on:
  push:
  workflow_dispatch:

jobs:
  postman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3.4.0
        with:
          node-version: 14.x
      - name: Install deps
        run: npm install --production
      - name: Run server
        run: npm run start &
      - uses: matt-ball/newman-action@master
        with:
          collection: Bookshelf_API_Test.postman_collection.json
          environment: Bookshelf_API_Test.postman_environment.json
